### ISSUE TITLE
Unable to run Ensembl VEP in single-threaded mode

### ISSUE THREAD

**Issue by brunogrande** [ckandoth/vcf2maf#10]
Whenever I specify `--vep-forks 1` when running vcf2maf, I get the following error with Ensembl VEP. 

```
ERROR: Fork number must be greater than 1
```

For some reason, the authors of VEP would rather throw an error instead of simply ignoring the `--fork 1` option. If the default for vcf2maf was one thread, this wouldn't be a problem, but since the default is four, it would be convenient if I could manually run in single-threaded mode.

**Comment by ckandoth** [comment]
Thanks for pointing this out. I've handled it in the [v1.5.1](https://github.com/ckandoth/vcf2maf/releases/tag/v1.5.1) patch. vcf2maf actually defaults to 1 thread now, but I might change that later.

**Comment by brunogrande** [comment]
Thanks, Cyriac!
