### ISSUE TITLE
Error: unrecognized biotype "enhancer"

### ISSUE THREAD

**Issue by jjchang** [ckandoth/vcf2maf#12]
Hi,

Thank you for making this tool. I followed the instructions to download the latest version of vcf2maf (within the last week) and the v79 of VEP (although in the variant_effect_predictor.pl it says the version is v77).

The a *.vep.vcf file is generated, however the *.maf output terminates prematurely. The error I'm getting is 'ERROR: Unrecognized biotype "enhancer". Please update your hashes!'

I saw that this seems a bit similar to an earlier post, but the error message complains about a different biotype.

Can you please advise?

Jonathan

**Comment by jjchang** [comment]
Nevermind. I cloned the master branch and it seems to work now.
I guess the code in the master branch is more updated than using the following code/link?
curl -LO https://github.com/ckandoth/vcf2maf/archive/master.zip

Jonathan

**Comment by ckandoth** [comment]
Thanks for pulling the latest branch. Ensembl often adds new kinds of biotypes that vcf2maf needs to know how to handle. I keep the master branch up to date, and push a stable version when a substantial number of edits/additions have been made.
