### ISSUE TITLE
maf2vcf.pl: Write all to one vcf

### ISSUE THREAD

**Issue by lujonathanh** [ckandoth/vcf2maf#14]
Hello,

I would like to write all the mutations in my maf file to the same vcf, rather than many different vcfs that are matched. To do this, I must create one long header containing all the samples, rather than only the tumor-sample pair. Do you recommend any method to do so?

Thank you!

Jonathan

**Comment by lujonathanh** [comment]
I found my answer: pyVCF provides a convenient way of changing headers. Sorry for the bother.

**Comment by ckandoth** [comment]
Hi Jonathon. Note that maf2vcf will now support a proper multisample VCF output.
