### ISSUE TITLE
a potential bug in vcf2maf.pl

### ISSUE THREAD

**Issue by qwangmsk** [ckandoth/vcf2maf#15]
Hi Cyriac, there may be a bug in line 537 in vcf2maf.pl. For normal sample, $nrm_depths[$var_allele_idx] can be zero in many cases. However, if $nrm_depths[$var_allele_idx] is 0, lines 539 and 540 will not be executed. To calculate $nrm_info{DP}, it may make more sense to use "if (( defined $nrm_depths[0] and defined $nrm_depths[$var_allele_idx] ) ..." in this line, instead of "if(( $nrm_depths[0] and $nrm_depths[$var_allele_idx] ) ..." 

Qingguo

**Comment by ckandoth** [comment]
Thanks Qingguo, this is now fixed in the master branch. ~CK

**Comment by qwangmsk** [comment]
In line 430, it is better to use "if(( defined $tum_depths[0] and defined $tum_depths[$var_allele_idx] ) ..." instead of "if(( $tum_depths[0] and $tum_depths[$var_allele_idx] ) ..." as well...

**Comment by ckandoth** [comment]
Thanks. Fixed in master.
