### ISSUE TITLE
maf2maf for VarScan tab delimited output

### ISSUE THREAD

**Issue by fpbarthel** [ckandoth/vcf2maf#16]
Would it be possible to make maf2maf work for the standard tab delimited varscan output? VarScan output is not the same as MAF, but it's similar, as it's tab delimited. Positions are the same as in the VCF format. I can share a sample file if that helps.

Floris

**Comment by ckandoth** [comment]
[At this link](https://github.com/ckandoth/vcf2maf/blob/master/data/minimalist_test_maf.tsv) you'll find a sample minimalist MAF file that maf2maf accepts. And for comparison, [this link](http://varscan.sourceforge.net/somatic-calling.html#somatic-output) lists the fields in VarScan output. For the most part, it looks like you'll simply need to change the column names to get maf2maf to work. To have maf2maf to parse out allele-counts, you can set `--nrm-rad-col normal_reads1`, `--nrm-vad-col normal_reads2`, `--tum-rad-col tumor_reads1`, etc.

**Comment by fpbarthel** [comment]
The biggest issue I think is the difference in start/end/ref/var reported in MAF compared to VCF and VarScan output. The VarScan output is more similar to VCF (the positions reported are the same) but there are still some major differences. I use the following R-code to convert the VarScan output to MAF(lite):

signs = substr(f$alt_allele,1,1)
  vartype = sapply(signs, function(sign) {
    if(sign == '+')
      return('INS')
    else if (sign == '-')
      return('DEL')
    else if (length(sign) > 0)
      return('SNP')
    else
      stop("No sign")
  })
  
  idx = which(vartype == 'INS')
  f$start[idx] = f$start[idx]
  f$end[idx] = f$start[idx] + 1
  f$ref_allele[idx] = "-"
  f$alt_allele[idx] = substr(f$alt_allele[idx],2,nchar(as.character(f$alt_allele[idx])))
  
  idx = which(vartype == 'DEL')
  f$start[idx] = f$start[idx] + 1
  f$ref_allele[idx] = substr(f$alt_allele[idx],2,nchar(as.character(f$alt_allele[idx])))
  f$alt_allele[idx] = "-"
  f$end[idx] = f$start[idx] + nchar(f$ref_allele[idx]) - 1

**Comment by ckandoth** [comment]
Is there a reason you don't want to use the VarScan VCF format output? I can help you troubleshoot whatever that reason may be. Otherwise, this is a feature request, which will take time.

**Comment by fpbarthel** [comment]
It's not a big issue. I've solved this issue for my own use using scripts in between but I'm guessing other people might be running into the same issue. VarScan post-processing modules are designed better to deal with native input than VCF input and don't always have the option to output VCF.

**Comment by ckandoth** [comment]
A lot of VarScan's downstream false-positive filtering steps have been implemented [in this script](https://github.com/ckandoth/variant-filter) which supports VCFs. Also lookup `bcftools annotate` and `bcftools filter` which are much more powerful for merging and post-processing VCFs.

**Comment by tedtoal** [comment]
Varscan still has problems with its VCF format as of v2.4.2.

**Comment by ckandoth** [comment]
@tedtoal As described above, only MAF-like or VCF-like allele representations are supported. If you still think there's a problem, please open a new issue, with a sample input file to help reproduce it.
