### ISSUE TITLE
Use of uninitialized value $effect in pattern match 

### ISSUE THREAD

**Issue by adbeggs** [ckandoth/vcf2maf#17]
Hi

I am having a recurrent issue with vcf2maf. I have used VEP to annotate my multi sample VCF file. It keeps giving me the error below. Initially I was using SNPeff and I saw that it had problems with this so I then used VEP, but the problem still occurs:

Use of uninitialized value in numeric eq (==) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 611, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 772, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 773, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 774, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 775, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 776, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 777, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 778, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 779, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 780, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 781, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 782, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 783, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 784, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 785, <GEN1> line 1073.
Use of uninitialized value $effect in pattern match (m//) at /home/abeggs/vcf2maf-master/vcf2maf.pl line 786, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 787, <GEN1> line 1073.
Use of uninitialized value $effect in string eq at /home/abeggs/vcf2maf-master/vcf2maf.pl line 788, <GEN1> line 1073.

The only issue that I can think off is that I am using the new Illumina aligner Isaac followed by Strelka, however I have stripped all the extrataneous stuff it puts in with bcftools

**Comment by ckandoth** [comment]
Instead of feeding in a pre-annotated MAF using `--input-vep`, I'd recommend you allow vcf2maf to run VEP by using `--input-vcf`. This allows vcf2maf to use all the VEP runtime arguments [as shown here](https://github.com/ckandoth/vcf2maf/blob/master/vcf2maf.pl#L263). Since MAFs are based on having tumor-normal pairs, please [click here](https://www.biostars.org/p/108112/#108816) to understand the caveats of using multisample VCFs from population-calling.

**Comment by adbeggs** [comment]
Thanks! Will try this and report back, but looks good.

**Comment by ckandoth** [comment]
Closing issue. Please reopen if you run into a similar bug.
