### ISSUE TITLE
SNP were annotated as DNP

### ISSUE THREAD

**Issue by qwangmsk** [ckandoth/vcf2maf#18]
For SNPs in input MAF, e.g. a SNP with Reference_Allele being 'G' and Tumor_Seq_Allele1 being 'A', if the Tumor_Seq_Allele2 is '-', maf2maf will annotate such SNPs as DNP, i.e. in the resulting annotation file,  Reference_Allele becomes 'GG' and Tumor_Seq_Allele1 is 'G' and Tumor_Seq_Allele2 is 'GA'. 

Please kindly fix this issue if possible, because they are not DNP.

Qingguo

**Comment by ckandoth** [comment]
Thanks again for reporting this. It has been fixed in v1.5.4. Please reopen this issue if you run into the same problem again.
